#!/usr/bin/env bash
set -euo pipefail
python -m compileall -q app.py panel agent tests
bash -n installer/install.sh installer/install-0.8.sh installer/upgrade.sh installer/upgrade-0.8.sh installer/nvp-migration-stage installer/configure-mail.sh installer/configure-sftp.sh agent/nvpctl tests/ci/*.sh
python tests/smoke_test.py
python tests/vault_test.py
python tests/integrations_test.py
python tests/provider_backup_test.py
python tests/trust_test.py
python tests/hosting_features_test.py
python tests/package_impact_test.py
python tests/resource_usage_agent_test.py
python tests/resource_usage_test.py
python tests/bandwidth_accounting_test.py
python tests/site_controls_agent_test.py
python tests/site_controls_test.py
python tests/whm_bulk_package_test.py
python tests/whm_bulk_status_test.py
python tests/schedules_test.py
python tests/accounts_scope_test.py
python tests/database_agent_test.py
python tests/database_access_test.py
python tests/database_lifecycle_test.py
python tests/postgres_access_agent_test.py
python tests/postgres_access_test.py
python tests/mail_policy_test.py
python tests/mail_password_rotation_test.py
python tests/mail_automation_test.py
python tests/mail_sieve_test.py
python tests/mail_queue_controls_test.py
python tests/mail_delivery_trace_test.py
python tests/transfer_policy_test.py
python tests/advanced_ops_test.py
python tests/migration_adapters_test.py
python tests/migration_center_test.py
python tests/server_agent_test.py
python tests/server_lifecycle_test.py
python tests/fleet_orchestration_test.py
python tests/module_registry_test.py
python tests/extension_hub_test.py
python tests/platform_08_parity_test.py
python tests/entitlements_test.py
python tests/session_revocation_test.py
python tests/domain_agent_test.py
python tests/domain_lifecycle_test.py
python tests/dynamic_dns_test.py
python tests/autossl_preflight_test.py
python tests/autossl_test.py
python tests/autossl_routes_test.py
python tests/deliverability_test.py
python tests/domain_health_test.py
python tests/domain_guardian_test.py
python tests/doctor_remediation_test.py
python tests/change_safety_test.py
python tests/wordpress_agent_test.py
python tests/wordpress_lifecycle_test.py
python tests/wordpress_components_test.py
python tests/wordpress_updates_routes_test.py
python tests/wordpress_staging_agent_test.py
python tests/wordpress_staging_test.py
python tests/wordpress_selective_agent_test.py
python tests/wordpress_publish_history_test.py
python tests/wordpress_smart_guard_test.py
python tests/release_contract_test.py
